apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog-site
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-blog-site
  template:
    metadata:
      labels:
        app: my-blog-site
    spec:
      containers:
      - name: my-blog-site-container
        image: ghcr.io/soumik-mukherjee/my-blog-site:0.1.0-dev.1
        # image: docker.io/soumik/my-blog-site:0.1.0-dev.1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: github-docker-registry-secret 
