apiVersion: v1
kind: Service
metadata:
  name: my-blog-site
spec:
  type: ClusterIP
  selector:
    app: my-blog-site
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
